import Head from 'next/head';
import FlexNav from '../components/FlexNav';
import FlexWrap from '../components/FlexWrap';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <FlexNav />
        <FlexWrap />
      </main>
    </div>
  );
}
