import Head from 'next/head';
import FlexNav from '../components/FlexNav';
import FlexWrap from '../components/FlexWrap';

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-[#e3e2e2] h-screen'>
        <FlexNav />
        <FlexWrap />
      </main>
    </div>
  );
}
